services: 
  server:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: velo-server
    command: npm run start:dev
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - ${PORT}:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    networks:
      - velo-network
      
  db:
    image: postgres
    restart: always
    container_name: velo-postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - velo-network

networks:
  velo-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local